name: Build

on: [push]

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer Downloads
      uses: actions/cache@v1
      with:
       path: ${{ steps.composer-cache.outputs.dir }}
       key: composer-${{ hashFiles('**/composer.json') }}

    - uses: php-actions/composer@v2

    - name: Install curl zip
      run: sudo apt-get update && sudo apt-get install -y curl zip

    - name: PHPStan
      run: vendor/bin/phpstan analyse -l 6 src

    - name: PHPCS
      run: vendor/bin/phpcs --standard=PSR12 src

    - name: PHPUnit
      run: ls && vendor/bin/phpunit -c ./phpunit.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
       file: build/logs/clover.xml
       flags: unittests
       name: codecov-umbrella
       fail_ci_if_error: true
