name: Dockerize

on:
  push:
   tags:
    - 'v*.*.*'
  create:
   tags:
    - 'v*.*.*'

 

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Define release variable
      run: |
          echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

    - name: Define version variables
      run: |
          echo "PATCH_VERSION="${RELEASE_VERSION:1} >> $GITHUB_ENV
          echo "MINOR_VERSION="$(echo ${RELEASE_VERSION:1} | sed 's/\.[0-9]*$//') >> $GITHUB_ENV
          echo "MAJOR_VERSION="$(echo ${RELEASE_VERSION:1} | sed 's/\.[0-9]*\.[0-9]*$//') >> $GITHUB_ENV

    - name: Build image
      run: docker build -t docker.pkg.github.com/sigmie/crawler/crawler:${PATCH_VERSION} -t docker.pkg.github.com/sigmie/crawler/crawler:${MINOR_VERSION} -t docker.pkg.github.com/sigmie/crawler/crawler:${MAJOR_VERSION} .

    - name: Authenticate docker
      run: docker login docker.pkg.github.com --username nicoorfi --password ${{ secrets.GITHUB_TOKEN }}

    - name: Push images
      run:  docker push docker.pkg.github.com/sigmie/crawler/crawler:${RELEASE_VERSION:1}
