name: Dockerize

on:
  create:
   tags:
    - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Define release variable
      run: |
          echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

    - name: Define version variables
      run: |
          echo "PATCH_VERSION="${RELEASE_VERSION:1} >> $GITHUB_ENV
          echo "MINOR_VERSION="$(echo ${RELEASE_VERSION:1} | sed 's/\.[0-9]*$//') >> $GITHUB_ENV
          echo "MAJOR_VERSION="$(echo ${RELEASE_VERSION:1} | sed 's/\.[0-9]*\.[0-9]*$//') >> $GITHUB_ENV

    - name: Build image
      run: docker build -t ghcr.io/sigmie/crawler:${PATCH_VERSION} -t ghcr.io/sigmie/crawler:${MINOR_VERSION} -t ghcr.io/sigmie/crawler:${MAJOR_VERSION} .

    - name: Authenticate docker
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u nicoorfi --password-stdin

    - name: Push images
      run: |
        docker push ghcr.io/sigmie/crawler:${MINOR_VERSION}
        docker push ghcr.io/sigmie/crawler:${MAJOR_VERSION}
        docker push ghcr.io/sigmie/crawler:${PATCH_VERSION}

